version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6-browsers
    steps:
      - checkout
      - run: yarn install
  test:
    docker:
      - image: circleci/node:6-browsers
    steps:
      - checkout
      - run: yarn test -- --single-run --no-progress
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test